package com.example.Calcfinity.logic

import androidx.compose.runtime.MutableState
import androidx.compose.runtime.mutableStateOf

sealed class Limit {
    data class IntLimit(val value: Int) : Limit()
    data class DoubleLimit(val value: Double) : Limit()
}
data class foodItem(val value: MutableState<Int>, val name: String, val image:String, val limit : Int ?, val unit:String, val calories: Int, val carbs: Int, val proteins: Int, val fats: Int)


val foodList = listOf(
    foodItem(mutableStateOf(1),"Apple", "https://example.com/red-apple.jpg", 10, "piece", 52, 14, 0, 0),
    foodItem(mutableStateOf(1),"Banana", "https://example.com/banana.jpg", 5, "piece", 89, 23, 1, 0),
    foodItem(mutableStateOf(1),"Orange", "https://example.com/orange.jpg", 8, "piece", 47, 12, 1, 0),
    foodItem(mutableStateOf(1),"Grapes", "https://example.com/grapes.jpg", 1, "cup", 104, 27, 1, 0),
    foodItem(mutableStateOf(1),"Strawberries", "https://example.com/strawberries.jpg", 1, "cup", 49, 12, 1, 0),
    foodItem(mutableStateOf(1),"Broccoli", "https://example.com/broccoli.jpg", 1, "cup", 31, 6, 3, 0),
    foodItem(mutableStateOf(1),"Spinach", "https://example.com/spinach.jpg", 1, "cup", 7, 1, 1, 0),
    foodItem(mutableStateOf(1),"Tomato", "https://example.com/tomato.jpg", 5, "piece", 18, 4, 1, 0),
    foodItem(mutableStateOf(1),"Carrot", "https://example.com/carrot.jpg", 5, "piece", 25, 6, 1, 0),
    foodItem(mutableStateOf(1),"Potato", "https://example.com/potato.jpg", 3, "piece", 163, 37, 4, 0),
    foodItem(mutableStateOf(1),"Rice", "https://example.com/rice.jpg", 1, "cup", 205, 45, 4, 0),
    foodItem(mutableStateOf(1),"Pasta", "https://example.com/pasta.jpg", 1, "cup", 200, 43, 7, 1),
    foodItem(mutableStateOf(1),"Bread", "https://example.com/bread.jpg", 2, "slice", 77, 13, 3, 1),
    foodItem(mutableStateOf(1),"Egg", "https://example.com/egg.jpg", 3, "piece", 72, 0, 6, 5),
    foodItem(mutableStateOf(1),"Chicken Breast", "https://example.com/chicken-breast.jpg", 1, "piece", 165, 0, 31, 3),
    foodItem(mutableStateOf(1),"Beef", "https://example.com/beef.jpg", 5, "pound", 351, 0, 49, 22),
    foodItem(mutableStateOf(1),"Salmon", "https://example.com/salmon.jpg", 5, "pound", 208, 0, 39, 7),
    foodItem(mutableStateOf(1),"Tuna", "https://example.com/tuna.jpg", 5, "can", 109, 0, 27, 1),
    foodItem(mutableStateOf(1),"Milk", "https://example.com/milk.jpg", 1, "cup", 103, 12, 8, 2),
    foodItem(mutableStateOf(1),"Yogurt", "https://example.com/yogurt.jpg", 1, "cup", 149, 17, 9, 5),
    foodItem(mutableStateOf(1),"Cheese", "https://example.com/cheese.jpg", 5, "cup", 227, 1, 14, 18),
    foodItem(mutableStateOf(1),"Peanut Butter", "https://example.com/peanut-butter.jpg", 2, "tablespoon", 188, 7, 8, 16),
    foodItem(mutableStateOf(1),"Almonds", "https://example.com/almonds.jpg", 25, "cup", 207, 8, 7, 18),
    foodItem(mutableStateOf(1),"Olive Oil", "https://example.com/olive-oil.jpg", 1, "tablespoon", 119, 0, 0, 14),
    foodItem(mutableStateOf(1),"Avocado", "https://example.com/avocado.jpg", 5, "piece", 322, 17, 5, 30),
    foodItem(mutableStateOf(1),"Oatmeal", "https://example.com/oatmeal.jpg", 1, "cup", 166, 27, 6, 3),
    foodItem(mutableStateOf(1),"Brown Rice", "https://example.com/brown-rice.jpg", 1, "cup", 216, 45, 5, 2),
    foodItem(mutableStateOf(1),"Quinoa", "https://example.com/quinoa.jpg", 1, "cup", 222, 39, 8, 4),
    foodItem(mutableStateOf(1),"Lentils", "https://example.com/lentils.jpg", 1, "cup", 230, 40, 18, 1),
    foodItem(mutableStateOf(1),"Black Beans", "https://example.com/black-beans.jpg", 1, "cup", 227, 41, 15, 1),
    foodItem(mutableStateOf(1),"Tofu", "https://example.com/tofu.jpg", 5, "cup", 94, 2, 10, 6),
    foodItem(mutableStateOf(1),"Soy Milk", "https://example.com/soy-milk.jpg", 1, "cup", 105, 8, 7, 4),
    foodItem(mutableStateOf(1),"Almond Milk", "https://example.com/almond-milk.jpg", 1, "cup", 39, 1, 1, 3),
    foodItem(mutableStateOf(1),"Coconut Milk", "https://example.com/coconut-milk.jpg", 5, "cup", 277, 7, 3, 27),
    foodItem(mutableStateOf(1),"Green Tea", "https://example.com/green-tea.jpg", 1, "cup", 2, 0, 0, 0),
    foodItem(mutableStateOf(1),"Coffee", "https://example.com/coffee.jpg", 1, "cup", 2, 0, 0, 0),
    foodItem(mutableStateOf(1),"Dark Chocolate", "https://example.com/dark-chocolate.jpg", 1, "ounce", 155, 13, 2, 9),
    foodItem(mutableStateOf(1),"Honey", "https://example.com/honey.jpg", 1, "tablespoon", 64, 17, 0, 0),
    foodItem(mutableStateOf(1),"Maple Syrup", "https://example.com/maple-syrup.jpg", 1, "tablespoon", 52, 13, 0, 0),
    foodItem(mutableStateOf(1),"Ketchup", "https://example.com/ketchup.jpg", 1, "tablespoon", 16, 4, 0, 0),
    foodItem(mutableStateOf(1),"Mustard", "https://example.com/mustard.jpg", 1, "tablespoon", 6, 1, 0, 0),
    foodItem(mutableStateOf(1),"Mayonnaise", "https://example.com/mayonnaise.jpg", 1, "tablespoon", 94, 0, 0, 10),
    foodItem(mutableStateOf(1),"Salsa", "https://example.com/salsa.jpg", 5, "cup", 18, 4, 1, 0),
    foodItem(mutableStateOf(1),"Hummus", "https://example.com/hummus.jpg", 5, "cup", 197, 17, 8, 10),
    foodItem(mutableStateOf(1),"Guacamole", "https://example.com/guacamole.jpg", 5, "cup", 322, 17, 5, 30),
    foodItem(mutableStateOf(1),"Pita Bread", "https://example.com/pita-bread.jpg", 1, "piece", 165, 33, 5, 1),
    foodItem(mutableStateOf(1),"Tortilla", "https://example.com/tortilla.jpg", 1, "piece", 97, 16, 2, 2),
    foodItem(mutableStateOf(1),"Bagel", "https://example.com/bagel.jpg", 1, "piece", 245, 51, 9, 1),
    foodItem(mutableStateOf(1),"Muffin", "https://example.com/muffin.jpg", 1, "piece", 374, 49, 5, 17),
    foodItem(mutableStateOf(1),"Donut", "https://example.com/donut.jpg", 1, "piece", 195, 22, 3, 10),
    foodItem(mutableStateOf(1),"Pizza", "https://example.com/pizza.jpg", 1, "slice", 285, 33, 12, 10),
    foodItem(mutableStateOf(1),"Hamburger", "https://example.com/hamburger.jpg", 1, "piece", 254, 28, 13, 10),
    foodItem(mutableStateOf(1),"French Fries", "https://example.com/french-fries.jpg", 1, "cup", 365, 48, 4, 17),
    foodItem(mutableStateOf(1),"Popcorn", "https://example.com/popcorn.jpg", 1, "cup", 31, 6, 1, 0),
    foodItem(mutableStateOf(1),"Chips", "https://example.com/chips.jpg", 1, "ounce", 155, 15, 2, 10),
    foodItem(mutableStateOf(1),"Cookies", "https://example.com/cookies.jpg", 2, "piece", 156, 18, 2, 8),
    foodItem(mutableStateOf(1),"Ice Cream", "https://example.com/ice-cream.jpg", 5, "cup", 137, 16, 2, 7),
    foodItem(mutableStateOf(1),"Cake", "https://example.com/cake.jpg", 1, "slice", 235, 28, 3, 12),
    foodItem(mutableStateOf(1),"Brownie", "https://example.com/brownie.jpg", 1, "piece", 135, 16, 2, 7),
    foodItem(mutableStateOf(1),"Peanuts", "https://example.com/peanuts.jpg", 25, "cup", 207, 6, 9, 18),
    foodItem(mutableStateOf(1),"Cashews", "https://example.com/cashews.jpg", 25, "cup", 193, 9, 5, 16),
    foodItem(mutableStateOf(1),"Walnuts", "https://example.com/walnuts.jpg", 25, "cup", 193, 4, 5, 19),
    foodItem(mutableStateOf(1),"Raisins", "https://example.com/raisins.jpg", 5, "cup", 129, 34, 1, 0),
    foodItem(mutableStateOf(1),"Dates", "https://example.com/dates.jpg", 3, "piece", 67, 18, 1, 0),
    foodItem(mutableStateOf(1),"Cranberries", "https://example.com/cranberries.jpg", 5, "cup", 25, 7, 0, 0),
    foodItem(mutableStateOf(1),"Blueberries", "https://example.com/blueberries.jpg", 1, "cup", 84, 21, 1, 0),
    foodItem(mutableStateOf(1),"Raspberries", "https://example.com/raspberries.jpg", 1, "cup", 64, 15, 1, 1),
    foodItem(mutableStateOf(1),"Blackberries", "https://example.com/blackberries.jpg", 1, "cup", 62, 14, 2, 1),
    foodItem(mutableStateOf(1),"Kiwi", "https://example.com/kiwi.jpg", 2, "piece", 92, 20, 2, 1),
    foodItem(mutableStateOf(1),"Pineapple", "https://example.com/pineapple.jpg", 1, "cup", 82, 22, 1, 0),
    foodItem(mutableStateOf(1),"Mango", "https://example.com/mango.jpg", 1, "piece", 135, 36, 1, 1),
    foodItem(mutableStateOf(1),"Papaya", "https://example.com/papaya.jpg", 1, "cup", 55, 15, 1, 0),
    foodItem(mutableStateOf(1),"Watermelon", "https://example.com/watermelon.jpg", 1, "cup", 46, 12, 1, 0),
    foodItem(mutableStateOf(1),"Cantaloupe", "https://example.com/cantaloupe.jpg", 1, "cup", 54, 14, 1, 0),
    foodItem(mutableStateOf(1),"Honeydew Melon", "https://example.com/honeydew-melon.jpg", 1, "cup", 64, 16, 1, 0),
    foodItem(mutableStateOf(1),"Grapefruit", "https://example.com/grapefruit.jpg", 5, "piece", 52, 13, 1, 0),
    foodItem(mutableStateOf(1),"Lemon", "https://example.com/lemon.jpg", 1, "piece", 17, 6, 1, 0),
    foodItem(mutableStateOf(1),"Lime", "https://example.com/lime.jpg", 1, "piece", 20, 7, 0, 0),
    foodItem(mutableStateOf(1),"Garlic", "https://example.com/garlic.jpg", 1, "clove", 4, 1, 0, 0),
    foodItem(mutableStateOf(1),"Onion", "https://example.com/onion.jpg", 1, "piece", 44, 10, 1, 0),
    foodItem(mutableStateOf(1),"Bell Pepper", "https://example.com/bell-pepper.jpg", 1, "piece", 24, 6, 1, 0),
    foodItem(mutableStateOf(1),"Cucumber", "https://example.com/cucumber.jpg", 1, "piece", 16, 4, 1, 0),
    foodItem(mutableStateOf(1),"Celery", "https://example.com/celery.jpg", 1, "stalk", 6, 1, 0, 0),
    foodItem(mutableStateOf(1),"Lettuce", "https://example.com/lettuce.jpg", 1, "cup", 5, 1, 1, 0),
    foodItem(mutableStateOf(1),"Cabbage", "https://example.com/cabbage.jpg", 1, "cup", 22, 5, 1, 0),
    foodItem(mutableStateOf(1),"Mushrooms", "https://example.com/mushrooms.jpg", 1, "cup", 21, 3, 3, 0),
    foodItem(mutableStateOf(1),"Asparagus", "https://example.com/asparagus.jpg", 1, "cup", 40, 5, 5, 0),
    foodItem(mutableStateOf(1),"Green Beans", "https://example.com/green-beans.jpg", 1, "cup", 31, 7, 2, 0),
    foodItem(mutableStateOf(1),"Corn", "https://example.com/corn.jpg", 1, "ear", 111, 21, 3, 1),
    foodItem(mutableStateOf(1),"Peas", "https://example.com/peas.jpg", 1, "cup", 134, 25, 8, 0),
    foodItem(mutableStateOf(1),"Beets", "https://example.com/beets.jpg", 1, "cup", 59, 13, 3, 0),
    foodItem(mutableStateOf(1),"Sweet Potato", "https://example.com/sweet-potato.jpg", 1, "piece", 103, 24, 2, 0),
    foodItem(mutableStateOf(1),"Yam", "https://example.com/yam.jpg", 1, "piece", 158, 37, 2, 0),
    foodItem(mutableStateOf(1),"Squash", "https://example.com/squash.jpg", 1, "cup", 42, 10, 1, 0),
    foodItem(mutableStateOf(1),"Zucchini", "https://example.com/zucchini.jpg", 1, "cup", 21, 4, 2, 0),
    foodItem(mutableStateOf(1),"Eggplant", "https://example.com/eggplant.jpg", 1, "cup", 35, 9, 1, 0),
    foodItem(mutableStateOf(1),"Cauliflower", "https://example.com/cauliflower.jpg", 1, "cup", 25, 5, 2, 0),
    foodItem(mutableStateOf(1),"Brussels Sprouts", "https://example.com/brussels-sprouts.jpg", 1, "cup", 38, 8, 3, 0),
    foodItem(mutableStateOf(1),"Artichoke", "https://example.com/artichoke.jpg", 1, "piece", 60, 13, 4, 0),
    foodItem(mutableStateOf(1),"Chia Seeds", "https://example.com/chia-seeds.jpg", 2, "tablespoon", 138, 12, 5, 9),
    foodItem(mutableStateOf(1),"Flaxseeds", "https://example.com/flaxseeds.jpg", 2, "tablespoon", 75, 4, 3, 6),
    foodItem(mutableStateOf(1),"Sunflower Seeds", "https://example.com/sunflower-seeds.jpg", 25, "cup", 187, 7, 6, 16),
    foodItem(mutableStateOf(1),"Pumpkin Seeds", "https://example.com/pumpkin-seeds.jpg", 25, "cup", 180, 4, 9, 15),
    foodItem(mutableStateOf(1),"Hemp Seeds", "https://example.com/hemp-seeds.jpg", 3, "tablespoon", 166, 3, 10, 14),
    foodItem(mutableStateOf(1),"Spirulina", "https://example.com/spirulina.jpg", 1, "tablespoon", 20, 2, 4, 0),
    foodItem(mutableStateOf(1),"Chlorella", "https://example.com/chlorella.jpg", 1, "tablespoon", 15, 1, 3, 0),
    foodItem(mutableStateOf(1),"Nutritional Yeast", "https://example.com/nutritional-yeast.jpg", 2, "tablespoon", 60, 4, 8, 1),
    foodItem(mutableStateOf(1),"Tempeh", "https://example.com/tempeh.jpg", 1, "cup", 320, 16, 31, 13),
    foodItem(mutableStateOf(1),"Edamame", "https://example.com/edamame.jpg", 1, "cup", 189, 14, 17, 8),
    foodItem(mutableStateOf(1),"Seitan", "https://example.com/seitan.jpg", 1, "cup", 370, 37, 31, 3),
    foodItem(mutableStateOf(1),"Miso", "https://example.com/miso.jpg", 1, "tablespoon", 35, 3, 2, 1),
    foodItem(mutableStateOf(1),"Tahini", "https://example.com/tahini.jpg", 2, "tablespoon", 178, 6, 5, 16),
    foodItem(mutableStateOf(1),"Coconut Water", "https://example.com/coconut-water.jpg", 1, "cup", 46, 6, 0, 0),
    foodItem(mutableStateOf(1),"Kombucha", "https://example.com/kombucha.jpg", 1, "cup", 30, 7, 0, 0),
    foodItem(mutableStateOf(1),"Ginger", "https://example.com/ginger.jpg", 1, "piece", 6, 1, 0, 0),
    foodItem(mutableStateOf(1),"Turmeric", "https://example.com/turmeric.jpg", 1, "teaspoon", 9, 2, 0, 0),
    foodItem(mutableStateOf(1),"Cinnamon", "https://example.com/cinnamon.jpg", 1, "teaspoon", 6, 1, 0, 0),
    foodItem(mutableStateOf(1),"Cayenne Pepper", "https://example.com/cayenne-pepper.jpg", 1, "teaspoon", 17, 3, 1, 0),
    foodItem(mutableStateOf(1),"Chili Powder", "https://example.com/chili-powder.jpg", 1, "teaspoon", 6, 1, 0, 0),
    foodItem(mutableStateOf(1),"Cumin", "https://example.com/cumin.jpg", 1, "teaspoon", 8, 1, 0, 1),
    foodItem(mutableStateOf(1),"Oregano", "https://example.com/oregano.jpg", 1, "teaspoon", 5, 1, 0, 0),
    foodItem(mutableStateOf(1),"Basil", "https://example.com/basil.jpg", 2, "tablespoon", 2, 0, 0, 0),
    foodItem(mutableStateOf(1),"Parsley", "https://example.com/parsley.jpg", 2, "tablespoon", 6, 1, 0, 0),
    foodItem(mutableStateOf(1),"Cilantro", "https://example.com/cilantro.jpg", 2, "tablespoon", 2, 0, 0, 0),
    foodItem(mutableStateOf(1),"Mint", "https://example.com/mint.jpg", 2, "tablespoon", 2, 0, 0, 0),
    foodItem(mutableStateOf(1),"Rosemary", "https://example.com/rosemary.jpg", 1, "teaspoon", 2, 0, 0, 0),
    foodItem(mutableStateOf(1),"Thyme", "https://example.com/thyme.jpg", 1, "teaspoon", 2, 0, 0, 0),
    foodItem(mutableStateOf(1),"Sage", "https://example.com/sage.jpg", 1, "teaspoon", 2, 0, 0, 0),
    foodItem(mutableStateOf(1),"Fennel Seeds", "https://example.com/fennel-seeds.jpg", 1, "teaspoon", 20, 4, 1, 0),
    foodItem(mutableStateOf(1),"Mustard Seeds", "https://example.com/mustard-seeds.jpg", 1, "teaspoon", 18, 2, 1, 1),
    foodItem(mutableStateOf(1),"Poppy Seeds", "https://example.com/poppy-seeds.jpg", 1, "tablespoon", 92, 3, 3, 8),
    foodItem(mutableStateOf(1),"Sesame Seeds", "https://example.com/sesame-seeds.jpg", 2, "tablespoon", 101, 3, 3, 9),
    foodItem(mutableStateOf(1),"Soy Sauce", "https://example.com/soy-sauce.jpg", 1, "tablespoon", 11, 1, 2, 0),
    foodItem(mutableStateOf(1),"Rice Vinegar", "https://example.com/rice-vinegar.jpg", 1, "tablespoon", 0, 0, 0, 0),
    foodItem(mutableStateOf(1),"Balsamic Vinegar", "https://example.com/balsamic-vinegar.jpg", 1, "tablespoon", 14, 2, 0, 0),
    foodItem(mutableStateOf(1),"Apple Cider Vinegar", "https://example.com/apple-cider-vinegar.jpg", 1, "tablespoon", 3, 0, 0, 0),
    foodItem(mutableStateOf(1),"Red Wine Vinegar", "https://example.com/red-wine-vinegar.jpg", 1, "tablespoon", 0, 0, 0, 0),
    foodItem(mutableStateOf(1),"White Wine Vinegar", "https://example.com/white-wine-vinegar.jpg", 1, "tablespoon", 0, 0, 0, 0),
    foodItem(mutableStateOf(1),"Dijon Mustard", "https://example.com/dijon-mustard.jpg", 1, "tablespoon", 10, 0, 0, 1),
    foodItem(mutableStateOf(1),"Fish Sauce", "https://example.com/fish-sauce.jpg", 1, "tablespoon", 10, 0, 1, 0),
    foodItem(mutableStateOf(1),"Tamari", "https://example.com/tamari.jpg", 1, "tablespoon", 10, 1, 2, 0),
    foodItem(mutableStateOf(1),"Liquid Aminos", "https://example.com/liquid-aminos.jpg", 1, "tablespoon", 5, 0, 1, 0),
    foodItem(mutableStateOf(1),"Worcestershire Sauce", "https://example.com/worcestershire-sauce.jpg", 1, "tablespoon", 15, 1, 0, 0),
    foodItem(mutableStateOf(1),"Hot Sauce", "https://example.com/hot-sauce.jpg", 1, "tablespoon", 6, 1, 0, 0),
    foodItem(mutableStateOf(1),"Sriracha", "https://example.com/sriracha.jpg", 1, "tablespoon", 7, 1, 0, 0),
    foodItem(mutableStateOf(1),"Wasabi", "https://example.com/wasabi.jpg", 1, "teaspoon", 10, 2, 0, 0),
    foodItem(mutableStateOf(1),"Gochujang", "https://example.com/gochujang.jpg", 1, "tablespoon", 20, 3, 1, 0),
    foodItem(mutableStateOf(1),"Mirin", "https://example.com/mirin.jpg", 1, "tablespoon", 35, 5, 0, 0),
    foodItem(mutableStateOf(1),"Rice Wine Vinegar", "https://example.com/rice-wine-vinegar.jpg", 1, "tablespoon", 0, 0, 0, 0),
    foodItem(mutableStateOf(1),"Ponzu", "https://example.com/ponzu.jpg", 1, "tablespoon", 10, 1, 0, 0),
    foodItem(mutableStateOf(1),"Teriyaki Sauce", "https://example.com/teriyaki-sauce.jpg", 1, "tablespoon", 20, 4, 0, 0),
    foodItem(mutableStateOf(1),"Hoisin Sauce", "https://example.com/hoisin-sauce.jpg", 1, "tablespoon", 35, 7, 1, 0),
    foodItem(mutableStateOf(1),"Oyster Sauce", "https://example.com/oyster-sauce.jpg", 1, "tablespoon", 15, 2, 1, 0),
    foodItem(mutableStateOf(1),"Plum Sauce", "https://example.com/plum-sauce.jpg", 1, "tablespoon", 25, 6, 0, 0),
    foodItem(mutableStateOf(1),"Chutney", "https://example.com/chutney.jpg", 1, "tablespoon", 20, 4, 0, 0),
    foodItem(mutableStateOf(1),"Curry Powder", "https://example.com/curry-powder.jpg", 1, "teaspoon", 6, 1, 0, 0),
    foodItem(mutableStateOf(1),"Garam Masala", "https://example.com/garam-masala.jpg", 1, "teaspoon", 5, 1, 0, 0),
    foodItem(mutableStateOf(1),"Chili Garlic Sauce", "https://example.com/chili-garlic-sauce.jpg", 1, "tablespoon", 15, 2, 0, 1),
    foodItem(mutableStateOf(1),"Harissa", "https://example.com/harissa.jpg", 1, "tablespoon", 30, 3, 1, 1),
    foodItem(mutableStateOf(1),"Ras el Hanout", "https://example.com/ras-el-hanout.jpg", 1, "teaspoon", 5, 1, 0, 0),
    foodItem(mutableStateOf(1),"Sumac", "https://example.com/sumac.jpg", 1, "teaspoon", 1, 0, 0, 0),
    foodItem(mutableStateOf(1),"Za'atar", "https://example.com/zaatar.jpg", 1, "teaspoon", 5, 1, 0, 0),
    foodItem(mutableStateOf(1),"Dukkah", "https://example.com/dukkah.jpg", 1, "tablespoon", 50, 3, 2, 4),
    foodItem(mutableStateOf(1),"Baharat", "https://example.com/baharat.jpg", 1, "teaspoon", 5, 1, 0, 0),
    foodItem(mutableStateOf(1),"Adobo Seasoning", "https://example.com/adobo-seasoning.jpg", 1, "teaspoon", 0, 0, 0, 0),
    foodItem(mutableStateOf(1),"Sazon Seasoning", "https://example.com/sazon-seasoning.jpg", 1, "teaspoon", 0, 0, 0, 0),
    foodItem(mutableStateOf(1),"Tajin Seasoning", "https://example.com/tajin-seasoning.jpg", 1, "teaspoon", 0, 0, 0, 0),
    foodItem(mutableStateOf(1),"Fajita Seasoning", "https://example.com/fajita-seasoning.jpg", 1, "teaspoon", 5, 1, 0, 0),
    foodItem(mutableStateOf(1),"Taco Seasoning", "https://example.com/taco-seasoning.jpg", 1, "teaspoon", 5, 1, 0, 0),
    foodItem(mutableStateOf(1),"Chili Powder Blend", "https://example.com/chili-powder-blend.jpg", 1, "teaspoon", 5, 1, 0, 0),
    foodItem(mutableStateOf(1),"Pumpkin Pie Spice", "https://example.com/pumpkin-pie-spice.jpg", 1, "teaspoon", 5, 1, 0, 0),
    foodItem(mutableStateOf(1),"Apple Pie Spice", "https://example.com/apple-pie-spice.jpg", 1, "teaspoon", 5, 1, 0, 0),
    foodItem(mutableStateOf(1),"Vegetable Stock", "https://example.com/vegetable-stock.jpg", 1, "cup", 10, 2, 0, 0),
    foodItem(mutableStateOf(1),"Chicken Stock", "https://example.com/chicken-stock.jpg", 1, "cup", 10, 0, 1, 0),
    foodItem(mutableStateOf(1),"Beef Stock", "https://example.com/beef-stock.jpg", 1, "cup", 10, 0, 1, 0),
    foodItem(mutableStateOf(1),"Fish Stock", "https://example.com/fish-stock.jpg", 1, "cup", 10, 0, 1, 0),
    foodItem(mutableStateOf(1),"Dashi", "https://example.com/dashi.jpg", 1, "cup", 10, 0, 1, 0),
    foodItem(mutableStateOf(1),"Vegetable Bouillon", "https://example.com/vegetable-bouillon.jpg", 1, "teaspoon", 5, 1, 0, 0),
    foodItem(mutableStateOf(1),"Chicken Bouillon", "https://example.com/chicken-bouillon.jpg", 1, "teaspoon", 5, 0, 1, 0),
    foodItem(mutableStateOf(1),"Beef Bouillon", "https://example.com/beef-bouillon.jpg", 1, "teaspoon", 5, 0, 1, 0),
    foodItem(mutableStateOf(1),"Fish Bouillon", "https://example.com/fish-bouillon.jpg", 1, "teaspoon", 5, 0, 1, 0),
    foodItem(mutableStateOf(1),"Coconut Milk", "https://example.com/coconut-milk.jpg", 1, "cup", 552, 13, 5, 57),
    foodItem(mutableStateOf(1),"Coconut Cream", "https://example.com/coconut-cream.jpg", 5, "cup", 552, 6, 3, 57),
    foodItem(mutableStateOf(1),"Almond Milk", "https://example.com/almond-milk.jpg", 1, "cup", 39, 1, 1, 3),
    foodItem(mutableStateOf(1),"Oat Milk", "https://example.com/oat-milk.jpg", 1, "cup", 120, 16, 3, 5),
    foodItem(mutableStateOf(1),"Rice Milk", "https://example.com/rice-milk.jpg", 1, "cup", 113, 23, 1, 2),
    foodItem(mutableStateOf(1),"Cashew Milk", "https://example.com/cashew-milk.jpg", 1, "cup", 25, 1, 0, 2),
    foodItem(mutableStateOf(1),"Hemp Milk", "https://example.com/hemp-milk.jpg", 1, "cup", 80, 1, 3, 5),
    foodItem(mutableStateOf(1),"Macadamia Milk", "https://example.com/macadamia-milk.jpg", 1, "cup", 100, 1, 0, 10),
    foodItem(mutableStateOf(1),"Hazelnut Milk", "https://example.com/hazelnut-milk.jpg", 1, "cup", 83, 2, 1, 7),
    foodItem(mutableStateOf(1),"Pistachio Milk", "https://example.com/pistachio-milk.jpg", 1, "cup", 90, 2, 1, 8),
    foodItem(mutableStateOf(1),"Pea Milk", "https://example.com/pea-milk.jpg", 1, "cup", 70, 2, 8, 4),
)